pipeline {
    agent any
    stages {
        stage ("First Stage") {
                    steps {
                        echo "First Step"
                    }
        }
        stage ("Second Stage") {
            steps {
                echo "Second Step"
            }
        }

        stage ("Third Stage") {
            steps {
                echo "Third Step"
            }
        }

        stage ("Fourth Stage") {
            steps {
                echo "Fourth Step"
            }
        }
        stage("Complete") {
            steps {
                echo "Build is complete!"
            }
        }

    }
}
